### ISSUE TITLE
On download failure, try another image server

### ISSUE THREAD

**Issue by Xon** [koroshiya/batoto-downloader-py#15]
Batoto has multiple image servers, rather than fail downloading outright; should try another image server.

Each page has a dropdown box with the name "location" which can be used to fetch the list of individual image servers.

**Comment by koroshiya** [comment]
I'll take a look later today. It should be very simple to implement.

**Comment by koroshiya** [comment]
Should now be fixed in 0ca796f2926172f00365a9e1226b11ed5a211f3e

**Comment by Xon** [comment]
batoto now implements a cdn which should be preferred over the individual image servers.
