### ISSUE TITLE
Scrub download list of empty lines

### ISSUE THREAD

**Issue by Xon** [koroshiya/batoto-downloader-py#16]
Every so often, a stray newline character gets into the list of items and requires manual fixup of the download file to get the application to handle it.

It would make sense to automatically skip download items which are blank lines or lines with just whitespace.

**Comment by koroshiya** [comment]
Untested, but should be fixed in commit 4265131e810f65d853f45a5cbd44896e52139617, which checks for short URLs both while loading, and while parsing.
