### ISSUE TITLE
Prefer CDN over direct image servers.

### ISSUE THREAD

**Issue by Xon** [koroshiya/batoto-downloader-py#17]
batoto now implements a cdn which should be preferred over the individual image servers.

**Comment by koroshiya** [comment]
Added in commit 0f49c28ef0c8ad9c08e7dc18110b25f92ac65a61
Pages coming from http://img.bato.to now attempt to use the CDN server first. If that fails, they revert to the img server.

**Comment by Xon** [comment]
Cheers
