### ISSUE TITLE
Links from RSS feed do not encode group into filename

### ISSUE THREAD

**Issue by Xon** [koroshiya/batoto-downloader-py#18]
The group name is available on the page to scrap on the 'group_select' element, just for some reason the RSS feed doesn't encode the group name into the URL like the normal links do.

It would be nice for this information to be preserved.

**Comment by koroshiya** [comment]
Hm... That's a hard one. I don't know why Batoto removes the group name from the RSS feed, and the linked pages don't contain the name of the group either.
I'll take a look later and see if there's a group ID or something that can be queried. If all else fails I can parse the series page and look for the corresponding link, group name and all, but loading the page for an entire series seems like a bit much.

**Comment by koroshiya** [comment]
Aaand done. Commit c0d6f8dea9725421470715b7e26f2904dfb62829
