### ISSUE TITLE
Support new semi-private Batoto

### ISSUE THREAD

**Issue by koroshiya** [koroshiya/batoto-downloader-py#19]
With Batoto becoming semi-private, the way images are loaded has changed a fair bit. The old URL scheme won't work anymore, and the image server subdomains may change.
1. URLs are now in the format: bato.to/reader#UUID
2. Images are loaded via AJAX, with calls to: http://bato.to/areader?id=UUID&p=pageNumber

The transition shouldn't be difficult.
Crawling for pages can still be done the same way, but by incrementing pageNumber instead of the page URL.
Series names can be extracted from the page title.

However, I'm currently getting frequent connection issues when trying to use the site in my web browser, and the subdomains haven't changed yet. As such, I won't begin working on this issue until some of the changes and teething issues associated with the overhaul are over with.

**Comment by Xon** [comment]
It looks like batoto now enforces cooie based session when allowing the next page, and supress_webtoon is now sent as a cookie rather than a URL parameter.

**Comment by koroshiya** [comment]
I believe I'm mostly done with the cookie-based session handling. Logins seem to work okay, but I appear to be missing something when trying to access the actual comic.

I'll take note of the suppress_webtoon parameter though. I hadn't gotten around to testing that yet.

I'll push all of the commits once I have the actual downloading working. Everything else should (theoretically) be done, but I still seem to be missing something with the page requests.

**Comment by Xon** [comment]
It looks like it is also doing a referrer check. I think I've got my local copy working now, just waiting for it to finish downloading a test version.

**Comment by koroshiya** [comment]
Thanks @Xon,
I've pulled your request. However, I'll be leaving this issue open for the time being.
My local copy has the group name and series name working, as well as HTTPS support, logins, and some other stuff I think would be beneficial. I'll try to finish it off tomorrow.

**Comment by Xon** [comment]
Great to hear. 

The extracting series name + group name + chapter is required since it is no longer encoded into the URL.

**Comment by koroshiya** [comment]
Okay, I've just pushed a bunch of commits.
I'll be leaving this issue open until I have support for HTTPS chapter URLs.

Some of the included updates are:
-series, group & chapter in downloaded url (eg. "MySeries - Ch.100 by MyGroup")
-support for logins (disabled until needed, but confirmed to be working)
-HTTPS support (works for login, but not chapter downloads...)
-added a modules downloading class, so if the user is missing something (eg. lxml) the program will download it for them
-smarter page parsing. Rather than looping until hitting an error, the initial chapter page is scraped for the total number of pages, and each one of those is formatted and parsed in turn.

...And some other junk.

**Comment by Xon** [comment]
I can't get pyOpenSSL  to install with the module auto-download:
```
testing lxml
testing certifi
testing pyOpenSSL
testing ndg.httpsclient
testing pyasn1
downloading: https://pypi.python.org/packages/source/p/pyOpenSSL/pyOpenSSL-0.15.1.tar.gz
hash of pyOpenSSL-0.15.1.tar.gz is f0a26070d6db0881de8bcc7846934b7c3c930d8f9c79d45883ee48984bc0d672
comparing to f0a26070d6db0881de8bcc7846934b7c3c930d8f9c79d45883ee48984bc0d672
Module pyOpenSSL still missing; assuming user stopped half way through
```

```
testing lxml
testing certifi
testing pyOpenSSL
testing ndg.httpsclient
testing pyasn1
downloading: https://pypi.python.org/packages/source/p/pyOpenSSL/pyOpenSSL-0.15.1.tar.gz
hash of pyOpenSSL-0.15.1.tar.gz is f0a26070d6db0881de8bcc7846934b7c3c930d8f9c79d45883ee48984bc0d672
comparing to f0a26070d6db0881de8bcc7846934b7c3c930d8f9c79d45883ee48984bc0d672
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "c:\Python27\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Storage\Downloads\batoto_rip\batoto-downloader\Updater.py", line 73, in doWork
    os.rename(m[3], m[0])
WindowsError: [Error 183] Cannot create a file when that file already exists

Module pyOpenSSL still missing; assuming user stopped half way through
```

**Comment by Xon** [comment]
Broken under windows:
```
OError: [Errno 2] No such file or directory: '/tmp/batoto.txt'
```

**Comment by koroshiya** [comment]
The tmp error is easy. It's just a debugging line which should have been removed anyway. I'll put up a commit shortly.
The pyOpenSSL error is a pain. It was working on one computer, but not this one. I'll take a look shortly, and if all else fails I may wind up running it through pip instead.

**Comment by Xon** [comment]
- getChapterInfo() urls can being accessed before being assigned
- Can you update .gitignore to include:
```
certifi
ndg
pyasn1
pyOpenSSL
```

**Comment by Xon** [comment]
Needs some filename so more restrictive file systems than Linux can download all chapters:

```
OError: [Errno 22] invalid mode ('wb') or filename: u'C:/Storage/Downloads/batoto_rip/Documents/Gunnm Mars Chronicle - Ch.11.2: log:011 (Second Half)
- The Skilled Physician by Team Pixie Dust.zip'
```
The : is forbidden on a bunch of file systems. And it could include a / which is forbidden on Linux.

**Comment by Xon** [comment]
Perhaps using https://github.com/un33k/python-slugify ?

**Comment by koroshiya** [comment]
I've fixed the tmp error, updated gitignore, added None checks for getChapterInfo, and dealt with the filenames (basic whitelist for the time being).
I'll experiment with pyOpenSSL in an hour or so.

**Comment by Xon** [comment]
:+1:

**Comment by koroshiya** [comment]
pyOpenSSL should behave a bit better now. I'll need to do more testing later though.

**Comment by Xon** [comment]
One thing I've noticed, the indexing process is a hell of a lot slower now.

**Comment by koroshiya** [comment]
This was because the full page was being downloaded instead of just the head. Indexing should be faster now.
I'll take another look tomorrow at further speed increases. I should be able to make indexing faster still by using workers, now that the number of pages is known ahead of time.
There also seems to be an issue with writing temp files... but I'll confirm that on another computer first, as it could just be my lousy connection.

**Comment by Xon** [comment]
:+1: 

Works much faster only doing the HEAD request on the required pages.

**Comment by koroshiya** [comment]
Ok, page indexing should be even faster now.
Page indexing now uses workers, so by default it'll index 4 at a time.
I've also re-ordered the file extensions attempted when indexing, so far fewer attempts should be needed.

**Comment by wyatt8740** [comment]
So, a question: where exactly do I need to go to specify my login info for the program? I'm not that familiar with python but grepping through it it looks like there's actually not a GUI for login information. Is that correct?

**Comment by koroshiya** [comment]
No need to login.
I started working on a login mechanism, but it turned out that the new Batoto doesn't require you to login in order to download, or to follow your RSS feed.
So for the time being, logins have been disabled. I'll enable the functionality if there's a need for it in the future.

**Comment by wyatt8740** [comment]
Alright. Linking straight to a manga page doesn't download anything, though. Should it? Or did I misread?

(this kind of link http://bato.to/comic/_/comics/hataraku-maousama-r6241/ )

**Comment by koroshiya** [comment]
That's how it was working, but the change to semi-private must have broken this.
I'll take a look later today.

**Comment by koroshiya** [comment]
Untested, but downloading a full series should be fixed in commit 1b9a8647da62cf4acdfb62ed3ebcbdae411dd930

**Comment by Xon** [comment]
@koroshiya batoto now appears to require you to be logged in to access older chapters.

**Comment by koroshiya** [comment]
Reading/downloading old chapters appears to be okay. It's just searching for them that's problematic, like if you were trying to download an entire series.
There are two lines you could change that should work around this. That's by uncommenting
`#menuSettings.AppendItem(menuItemLoginDialog)`
in URLParser.py, and by commenting out
`return True`
in loginIfNeeded in BatotoFrame.py.
Doing that, you can enter a username and password through the settings menu.

At the moment I'm thinking about whether to update this application, or just start fresh. I'm now on a computer with Python 3 instead, so I'd need to update most of the application to continue using or working on it. Also, I already started working on an Electron-based version, which is nicer in a lot of ways. But it doesn't have the same features right now, so it's not yet a replacement.

**Comment by Xon** [comment]
It looks like some batoto chapters hard require being logged in.

For chapter; f298adc3647aa09a, if you aren't logged in when getting the chapter info the following is thrown; 
```
    group = dom.xpath(".//*[@name='group_select']/option[@selected='selected']/text()")[0]
IndexError: list index out of range
```

The tweaks you suggested for the login bits don't work.

**Comment by koroshiya** [comment]
IIRC, nowadays only the last couple of chapters of a series are visible, and you need to login to read anything older.
Logins are also a PITA. A successful login sends you to one page, which gives you a cookie you need for access, but that page has a 302 error code and redirects you to another page. Most libraries follow redirects automatically, and don't store cookies from the redirecting page, which makes logging in a pain.

Tonight I'll upload the Electron-based version to GitHub. It doesn't have a working login either, but if I'm going to take a stab at getting the login to work, it'll be on that version.

**Comment by koroshiya** [comment]
Electron-based version here: https://github.com/koroshiya/batoto-downloader-node
It's pretty basic right now. No logins, no RSS, only basic settings, etc.

**Comment by Xon** [comment]
Looks like the page layout has changed again and now it can't find URLs to download

**Comment by koroshiya** [comment]
@Xon I have no plans to keep supporting the Python version. However, I have now updated the NodeJS version to work with the new URL format: https://github.com/koroshiya/batoto-downloader-node/commit/9a4428a6ed9aecff2d5da580d239c40880ba60d0

There's no guarantee that cnd2 will always be used. Could be cdn, could be img. So best to use regex rather than hard-coded "cdn2".

**Comment by Zaelot** [comment]
And now sadly Batoto is [closing](https://bato.to/forums/topic/28840-batoto-will-be-closing-permanently/). 😭

**Comment by koroshiya** [comment]
Damn, that sucks. I can understand Grumpy's reasoning, but it sounds like he just tried to do too much all on his own.
I'll close this issue and update the README once Batoto stops functioning.

**Comment by koroshiya** [comment]
Batoto is still hosting some content, but for the most part it seems like the site is in the middle of shutting down, and the page/url schemes have changed a bit. With the shutdown imminent, I'm now closing this issue and ruling out further development.
The code will remain in case anybody wants to adapt it to download from another site, or a Batoto clone pops up. (Or they just want to learn from the code, see how it works, etc.)
