### ISSUE TITLE
Being able to choose where the acrhives are downloaded to.

### ISSUE THREAD

**Issue by wizbright** [koroshiya/batoto-downloader-py#23]
Would be a great help if this could be implemented as an option as I am not a huge fan of dumping all the manga in the home folder.

**Comment by koroshiya** [comment]
I'll take a look at doing this next week. It should be very straightforward to implement.

**Comment by koroshiya** [comment]
Feature added in commit 77e5e99b05514f742f499efb4a78a2d627db2e8a
