### ISSUE TITLE
Discard RSS dates in the future

### ISSUE THREAD

**Issue by Xon** [koroshiya/batoto-downloader-py#24]
I'm not sure how, but it is sometimes possible for a chapter to be added with a date sometime in the future.

Recording a last check date about a week into the future isn't particularly useful.

**Comment by koroshiya** [comment]
Should be fixed as of commit 0228b06ecec0a2ca0084b63a41911ee2a5a4869b
Untested though. Will test this evening.

The current time is now compared against the last RSS read time twice: once before checking the RSS feed, and once after.
If the saved time is in the future, it's set to 2 days ago.
If the received time is in the future, we save the current time.
